--진찰부서표 테이블
CREATE TABLE DEPARTMENT (
    CODE CHAR(2),
    DNAME VARCHAR2(15) CONSTRAINT DEPARTMENT_DNAME_NN NOT NULL,
    CONSTRAINT DEPARTMENT_CODE_PK PRIMARY KEY (CODE)
);

INSERT INTO DEPARTMENT VALUES('MI', '외과');
INSERT INTO DEPARTMENT VALUES('NI', '내과');
INSERT INTO DEPARTMENT VALUES('SI', '피부과');
INSERT INTO DEPARTMENT VALUES('TI', '소아과');
INSERT INTO DEPARTMENT VALUES('VI', '산부인과');
INSERT INTO DEPARTMENT VALUES('WI', '비뇨기과');
COMMIT;

--진찰비 테이블
CREATE TABLE CHECKUP(
    SEQ NUMBER(1),
    LOAGE NUMBER(2) CONSTRAINT CHECKUP_LOAGE_NN NOT NULL,
    HIAGE NUMBER(3) CONSTRAINT CHECKUP_HIAGE_NN NOT NULL,
    FEE NUMBER(4) CONSTRAINT CHECKUP_FEE_NN NOT NULL,
    CONSTRAINT CHECKUP_SEQ_PK PRIMARY KEY(SEQ)
);

INSERT INTO CHECKUP VALUES(1, 0, 9, 7000);
INSERT INTO CHECKUP VALUES(2, 10, 19, 5000);
INSERT INTO CHECKUP VALUES(3, 20, 29, 8000);
INSERT INTO CHECKUP VALUES(4, 30, 39, 7000);
INSERT INTO CHECKUP VALUES(5, 40, 49, 4500);
INSERT INTO CHECKUP VALUES(6, 50, 120, 2300);
COMMIT;

CREATE TABLE DISCOUNT(
    SEQ NUMBER(1),
    LODAYS NUMBER(3) CONSTRAINT DISCOUNT_LODAYS_NN NOT NULL,
    HIDAYS NUMBER(4) CONSTRAINT DISCOUNT_HIDAYS_NN NOT NULL,
    RATE NUMBER(3,2) CONSTRAINT DISCOUNT_RATE_NN NOT NULL,
    CONSTRAINT DISCOUNT_SEQ_PK PRIMARY KEY(SEQ)
);

INSERT INTO DISCOUNT VALUES(1, 1, 9, 1.00);
INSERT INTO DISCOUNT VALUES(2, 10, 14, 0.85);
INSERT INTO DISCOUNT VALUES(3, 15, 19, 0.80);
INSERT INTO DISCOUNT VALUES(4, 20, 29, 0.77);
INSERT INTO DISCOUNT VALUES(5, 30, 99, 0.72);
INSERT INTO DISCOUNT VALUES(6, 100, 9999, 0.68);
COMMIT;

CREATE TABLE PATIENT(
    BUNHO NUMBER(1), -- 환자번호
    CODE CHAR(2) CONSTRAINT PATIENT_CODE_NN NOT NULL, -- 환자진찰코드
    DAYS NUMBER(4) CONSTRAINT PATIENT_DAYS_NN NOT NULL, -- 환자입원일수
    AGE NUMBER(3) CONSTRAINT PATIENT_AGE_NN NOT NULL, -- 환자 나이
    DNAME VARCHAR(15), -- 환자 진찰 부서명
    CHECKUP_FEE NUMBER(4), -- 진찰비
    HOSPITAL_FEE NUMBER(7), -- 입원비
    SUM NUMBER(8), -- 진료비
    CONSTRAINT PATIENT_BUNHO_PK PRIMARY KEY(BUNHO)
);




